<?xml version="1.0"?>
<package format="2">
  <name>pal_pro_gripper_controller_configuration_gazebo</name>
  <version>0.0.2</version>
  <description>Controllers configuration for PAL pro gripper in Gazebo</description>

  <maintainer email="david.terkuile@pal-robotics.com">David ter Kuile</maintainer>
  <author email="david.terkuile@pal-robotics.com">David ter Kuile</author>
  
  <license>Proprietary</license>
  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>actionlib</exec_depend>
  <exec_depend>pal_pro_gripper_controller_configuration</exec_depend>
  <exec_depend>control_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

</package>
