<?xml version="1.0"?>
<package format="3">
  <name>pal_pro_gripper_grasp_check</name>
  <version>0.0.0</version>
  <description>Grasp controller to close with a determined error on position only
    so to skip overheating.</description>
  <maintainer email="matteovillani@pal-robotics.com">user</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclpy</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_pal</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  
  <build_depend>control_msgs</build_depend>
  <build_depend>trajectory_msgs</build_depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

